# Generated by Django 5.2.6 on 2025-09-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default='N/A', max_length=255)),
                ('city', models.CharField(default='Unknown City', max_length=100)),
                ('zip_code', models.CharField(default='0000', max_length=10)),
            ],
        ),
    ]
